export const data = [
    {
        client: "Chandan Kalita",
        name: "Chandan Deal",
        budget: "$5,000",
        assignee: "Michael Speed",
        stage: "Negotiating",
        date: "2025-10-01",
    },
    {
        client: "Michael Speed",
        name: "Some Deal 4",
        budget: "$7,000",
        assignee: "Michael Speed",
        stage: "Negotiating",
        date: "2025-10-12",
    },
    {
        client: "John Carter",
        name: "Kickback Deal",
        budget: "$10,000",
        assignee: "Amit Shah",
        stage: "Kickedback",
        date: "2025-09-29",
    },
    {
        client: "Priya Sharma",
        name: "Design Revamp",
        budget: "$8,500",
        assignee: "Anjali Verma",
        stage: "Active",
        date: "2025-11-01",
    },
    {
        client: "Rohit Mehra",
        name: "E-Commerce Setup",
        budget: "$12,000",
        assignee: "Vikas Yadav",
        stage: "Negotiating",
        date: "2025-10-15",
    },
    {
        client: "Alok Tiwari",
        name: "SEO Package",
        budget: "$3,200",
        assignee: "Michael Speed",
        stage: "Active",
        date: "2025-11-05",
    },
    {
        client: "Neha Patel",
        name: "Website Upgrade",
        budget: "$6,500",
        assignee: "Amit Shah",
        stage: "Active",
        date: "2025-10-25",
    },
    {
        client: "Arjun Das",
        name: "App Development",
        budget: "$14,000",
        assignee: "Anjali Verma",
        stage: "Kickedback",
        date: "2025-09-10",
    },
    {
        client: "Sonal Gupta",
        name: "Ad Campaign",
        budget: "$4,800",
        assignee: "Vikas Yadav",
        stage: "Active",
        date: "2025-11-02",
    },
    {
        client: "Karan Singh",
        name: "Brand Promotion",
        budget: "$9,000",
        assignee: "Michael Speed",
        stage: "Negotiating",
        date: "2025-10-08",
    },
    {
        client: "Simran Kaur",
        name: "Digital Marketing",
        budget: "$6,700",
        assignee: "Amit Shah",
        stage: "Active",
        date: "2025-11-03",
    },
    {
        client: "Ankit Raj",
        name: "Data Analytics",
        budget: "$11,000",
        assignee: "Vikas Yadav",
        stage: "Kickedback",
        date: "2025-09-20",
    },
    {
        client: "Rahul Joshi",
        name: "CRM Integration",
        budget: "$7,800",
        assignee: "Anjali Verma",
        stage: "Active",
        date: "2025-10-28",
    },
    {
        client: "Aisha Khan",
        name: "Content Strategy",
        budget: "$5,400",
        assignee: "Michael Speed",
        stage: "Negotiating",
        date: "2025-10-18",
    },
    {
        client: "Deepak Verma",
        name: "Market Research",
        budget: "$3,900",
        assignee: "Amit Shah",
        stage: "Active",
        date: "2025-11-04",
    },
    {
        client: "Pooja Rani",
        name: "Ad Shoot",
        budget: "$9,500",
        assignee: "Anjali Verma",
        stage: "Kickedback",
        date: "2025-09-22",
    },
    {
        client: "Varun Thakur",
        name: "Influencer Deals",
        budget: "$8,800",
        assignee: "Vikas Yadav",
        stage: "Active",
        date: "2025-11-06",
    },
    {
        client: "Meena Nair",
        name: "Logo Design",
        budget: "$2,500",
        assignee: "Amit Shah",
        stage: "Negotiating",
        date: "2025-10-03",
    },
    {
        client: "Aditya Jain",
        name: "Video Production",
        budget: "$10,500",
        assignee: "Michael Speed",
        stage: "Active",
        date: "2025-11-01",
    },
    {
        client: "Ishita Roy",
        name: "PR Campaign",
        budget: "$6,000",
        assignee: "Anjali Verma",
        stage: "Negotiating",
        date: "2025-10-09",
    },
];